name = "ethernet_io"
version = "0.1.0"
[dependencies]
#JITX3 = { path = "{SLM_ROOT}/JITX3" }
jsl = { git = "JITx-Inc/jsl", version = "0.9.1"}
ocdb = { git = "JITx-Inc/open-components-database", version = "3.21.0" }
connectors = { git = "JITx-Inc/connectors", version = "0.4.0" }
